package admin

import (
	"context"
	"crypto/rand"
	"embed"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"log/slog"
	"mime"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"

	"golang.org/x/crypto/bcrypt"
	"openlist-tvbox/internal/auth"
	"openlist-tvbox/internal/config"
	"openlist-tvbox/internal/logging"
	"openlist-tvbox/internal/openlist"
)

const (
	envAdminCode      = "OPENLIST_TVBOX_ADMIN_ACCESS_CODE"
	envAdminCodeHash  = "OPENLIST_TVBOX_ADMIN_ACCESS_CODE_HASH"
	secretFileName    = "admin_access_code_hash"
	setupCodeFileName = "admin_setup_code"
	maxConfigBodySize = 1 << 20
	sessionCookieName = "openlist_tvbox_admin_session"
	sessionTTL        = 12 * time.Hour
	maxAdminSessions  = 128
)

var adminBcryptCost = auth.DefaultBcryptCost

// Admin UI assets are generated by `pnpm build:admin` / `pnpm build`.
// assets/placeholder.txt keeps this embed pattern valid in clean Go builds.
//
//go:embed assets/*
var adminAssets embed.FS

type Server struct {
	configPath    string
	logger        *slog.Logger
	hash          string
	setupCodePath string
	setupCode     string
	onSaved       func(*config.Config)
	saveMu        sync.Mutex
	setupMu       sync.Mutex
	authLimiter   *auth.FailureLimiter
	logBuffer     *logging.Buffer
	shutdown      chan struct{}
	shutdownOnce  sync.Once
	sessionMu     sync.Mutex
	sessions      map[string]adminSession
	trustMu       sync.RWMutex
	trustXFF      bool
	publicBaseURL string
}

type adminSession struct {
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Options struct {
	ConfigPath string
	Listen     string
	Logger     *slog.Logger
	LogBuffer  *logging.Buffer
	OnSaved    func(*config.Config)
}

func NewServer(opts Options) (*Server, error) {
	state, err := loadAdminState(opts.ConfigPath)
	if err != nil {
		return nil, err
	}
	trustXFF := false
	publicBaseURL := ""
	if cfg, err := config.Load(opts.ConfigPath); err == nil {
		trustXFF = cfg.TrustXForwardedFor
		publicBaseURL = cfg.PublicBaseURL
	}
	if opts.Logger != nil {
		if state.Hash != "" {
			opts.Logger.Info("admin access code loaded")
		} else {
			opts.Logger.Warn("admin setup required; use the setup code file to create an access code", "admin_url", adminURL(opts.Listen), "setup_code_path", state.SetupCodePath)
		}
	}
	return &Server{
		configPath:    opts.ConfigPath,
		logger:        opts.Logger,
		hash:          state.Hash,
		setupCodePath: state.SetupCodePath,
		setupCode:     state.SetupCode,
		onSaved:       opts.OnSaved,
		authLimiter:   auth.NewFailureLimiter(auth.DefaultFailureLimit, auth.DefaultFailureCooldown),
		logBuffer:     opts.LogBuffer,
		shutdown:      make(chan struct{}),
		sessions:      map[string]adminSession{},
		trustXFF:      trustXFF,
		publicBaseURL: publicBaseURL,
	}, nil
}

func (s *Server) Shutdown() {
	s.shutdownOnce.Do(func() {
		close(s.shutdown)
	})
}

func (s *Server) Handler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("POST /admin/setup", s.requireSameOrigin(s.setup))
	mux.HandleFunc("POST /admin/login", s.requireSameOrigin(s.login))
	mux.HandleFunc("POST /admin/logout", s.requireSameOrigin(s.logout))
	mux.HandleFunc("POST /admin/access-code", s.requireSameOrigin(s.requireAuth(s.updateAdminAccessCode)))
	mux.HandleFunc("GET /admin/session", s.session)
	mux.HandleFunc("GET /admin/config/meta", s.requireAuth(s.meta))
	mux.HandleFunc("GET /admin/config", s.requireAuth(s.getConfig))
	mux.HandleFunc("GET /admin/logs", s.requireAuth(s.logs))
	mux.HandleFunc("GET /admin/logs/stream", s.requireAuth(s.streamLogs))
	mux.HandleFunc("POST /admin/config/validate", s.requireSameOrigin(s.requireAuth(s.validateConfig)))
	mux.HandleFunc("POST /admin/backend/test", s.requireSameOrigin(s.requireAuth(s.testBackend)))
	mux.HandleFunc("PUT /admin/config", s.requireSameOrigin(s.requireAuth(s.putConfig)))
	mux.HandleFunc("GET /admin/assets/", s.asset)
	mux.HandleFunc("GET /admin", s.index)
	mux.HandleFunc("GET /admin/", s.index)
	return mux
}

func (s *Server) requireSameOrigin(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !s.sameOrigin(r) {
			writeAdminError(w, http.StatusForbidden, "request.cross_origin", "cross-origin admin request rejected", nil)
			return
		}
		next(w, r)
	}
}

func (s *Server) requireAuth(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if s.adminHash() == "" {
			writeAdminError(w, http.StatusForbidden, "admin.setup_required", "admin setup required", nil)
			return
		}
		if !s.validSession(r) {
			writeAdminError(w, http.StatusUnauthorized, "auth.unauthorized", "unauthorized", nil)
			return
		}
		next(w, r)
	}
}

func (s *Server) adminHash() string {
	s.setupMu.Lock()
	defer s.setupMu.Unlock()
	return s.hash
}

func (s *Server) setup(w http.ResponseWriter, r *http.Request) {
	s.setupMu.Lock()
	defer s.setupMu.Unlock()
	if s.hash != "" {
		writeAdminError(w, http.StatusConflict, "admin.already_initialized", "admin already initialized", nil)
		return
	}
	key := s.setupFailureKey(r)
	if s.authLimiter.Blocked(key) {
		s.logAuthFailure("admin setup throttled", r, "too_many_attempts")
		writeAdminError(w, http.StatusTooManyRequests, "auth.too_many_setup_attempts", "too many failed admin setup attempts", nil)
		return
	}
	var req struct {
		SetupCode  string `json:"setup_code"`
		AccessCode string `json:"access_code"`
	}
	dec := json.NewDecoder(io.LimitReader(r.Body, maxConfigBodySize+1))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		writeAdminError(w, http.StatusBadRequest, "request.invalid_json", "invalid setup json", map[string]any{"target": "setup"})
		return
	}
	if verifySetupCode(s.setupCode, req.SetupCode) != nil {
		if req.SetupCode != "" {
			s.authLimiter.RecordFailure(key)
			s.logAuthFailure("admin setup failed", r, "invalid_setup_code")
		}
		writeAdminError(w, http.StatusUnauthorized, "auth.unauthorized", "unauthorized", nil)
		return
	}
	hash, err := hashAdminCode(req.AccessCode)
	if err != nil {
		writeAdminErrorFromError(w, http.StatusBadRequest, err, "admin.access_code.invalid")
		return
	}
	secretPath := adminSecretPath(s.configPath)
	if err := os.WriteFile(secretPath, []byte(hash+"\n"), 0o600); err != nil {
		writeAdminError(w, http.StatusInternalServerError, "admin.setup_failed", "admin setup failed", nil)
		return
	}
	if s.setupCodePath != "" {
		if err := os.Remove(s.setupCodePath); err != nil && !errors.Is(err, os.ErrNotExist) {
			_ = os.Remove(secretPath)
			writeAdminError(w, http.StatusInternalServerError, "admin.setup_failed", "admin setup failed", nil)
			return
		}
	}
	s.hash = hash
	s.setupCode = ""
	s.setupCodePath = ""
	s.authLimiter.Clear(key)
	if err := s.issueSessionCookie(w, r); err != nil {
		writeAdminError(w, http.StatusInternalServerError, "admin.session_failed", "admin session failed", nil)
		return
	}
	if s.logger != nil {
		s.logger.Info("admin setup completed")
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true})
}

func (s *Server) login(w http.ResponseWriter, r *http.Request) {
	if s.adminHash() == "" {
		writeAdminError(w, http.StatusForbidden, "admin.setup_required", "admin setup required", nil)
		return
	}
	key := s.adminFailureKey(r)
	if s.authLimiter.Blocked(key) {
		s.logAuthFailure("admin login throttled", r, "too_many_attempts")
		writeAdminError(w, http.StatusTooManyRequests, "auth.too_many_login_attempts", "too many failed admin authentication attempts", nil)
		return
	}
	var req struct {
		AccessCode string `json:"access_code"`
	}
	dec := json.NewDecoder(io.LimitReader(r.Body, maxConfigBodySize+1))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		writeAdminError(w, http.StatusBadRequest, "request.invalid_json", "invalid login json", map[string]any{"target": "login"})
		return
	}
	if verifyAdminCode(s.adminHash(), req.AccessCode) != nil {
		if req.AccessCode != "" {
			s.authLimiter.RecordFailure(key)
			s.logAuthFailure("admin login failed", r, "invalid_access_code")
		}
		writeAdminError(w, http.StatusUnauthorized, "auth.unauthorized", "unauthorized", nil)
		return
	}
	s.authLimiter.Clear(key)
	if err := s.issueSessionCookie(w, r); err != nil {
		writeAdminError(w, http.StatusInternalServerError, "admin.session_failed", "admin session failed", nil)
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true})
}

func (s *Server) logout(w http.ResponseWriter, r *http.Request) {
	if cookie, err := r.Cookie(sessionCookieName); err == nil {
		s.sessionMu.Lock()
		delete(s.sessions, cookie.Value)
		s.sessionMu.Unlock()
	}
	s.clearSessionCookie(w, r)
	writeJSON(w, http.StatusOK, map[string]any{"ok": true})
}

func (s *Server) updateAdminAccessCode(w http.ResponseWriter, r *http.Request) {
	key := s.adminFailureKey(r)
	if s.authLimiter.Blocked(key) {
		s.logAuthFailure("admin access code update throttled", r, "too_many_attempts")
		writeAdminError(w, http.StatusTooManyRequests, "auth.too_many_login_attempts", "too many failed admin authentication attempts", nil)
		return
	}
	var req struct {
		CurrentAccessCode string `json:"current_access_code"`
		NewAccessCode     string `json:"new_access_code"`
	}
	dec := json.NewDecoder(io.LimitReader(r.Body, maxConfigBodySize+1))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		writeAdminError(w, http.StatusBadRequest, "request.invalid_json", "invalid access code json", map[string]any{"target": "access_code"})
		return
	}
	s.setupMu.Lock()
	defer s.setupMu.Unlock()
	if verifyAdminCode(s.hash, req.CurrentAccessCode) != nil {
		if req.CurrentAccessCode != "" {
			s.authLimiter.RecordFailure(key)
			s.logAuthFailure("admin access code update failed", r, "invalid_current_code")
		}
		writeAdminError(w, http.StatusUnauthorized, "auth.unauthorized", "unauthorized", nil)
		return
	}
	hash, err := hashAdminCode(req.NewAccessCode)
	if err != nil {
		writeAdminErrorFromError(w, http.StatusBadRequest, err, "admin.access_code.invalid")
		return
	}
	if err := os.WriteFile(adminSecretPath(s.configPath), []byte(hash+"\n"), 0o600); err != nil {
		writeAdminError(w, http.StatusInternalServerError, "admin.access_code.update_failed", "admin access code update failed", nil)
		return
	}
	s.hash = hash
	s.authLimiter.Clear(key)
	if s.logger != nil {
		s.logger.Info("admin access code updated", "client", auth.ClientHost(r, s.trustXForwardedFor()))
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true})
}

func (s *Server) session(w http.ResponseWriter, r *http.Request) {
	if s.adminHash() == "" {
		writeJSON(w, http.StatusOK, map[string]any{"authenticated": false, "setup_required": true})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"authenticated": s.validSession(r), "setup_required": false})
}

func (s *Server) meta(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, map[string]any{
		"mode":     "editable",
		"format":   "json",
		"editable": true,
		"path":     s.configPath,
	})
}

func (s *Server) getConfig(w http.ResponseWriter, r *http.Request) {
	cfg, err := config.Load(s.configPath)
	if err != nil {
		writeAdminError(w, http.StatusInternalServerError, "config.load_failed", "config load failed", nil)
		return
	}
	writeJSON(w, http.StatusOK, redactedConfig(*cfg))
}

func (s *Server) logs(w http.ResponseWriter, r *http.Request) {
	limit := parseLogLimit(r.URL.Query().Get("limit"), 300, 1000)
	level := parseLogLevel(r.URL.Query().Get("level"))
	entries := []logging.Entry{}
	if s.logBuffer != nil {
		entries = s.logBuffer.Snapshot(limit, level)
	}
	writeJSON(w, http.StatusOK, map[string]any{"logs": entries})
}

func (s *Server) streamLogs(w http.ResponseWriter, r *http.Request) {
	if s.logBuffer == nil {
		http.NotFound(w, r)
		return
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		writeAdminError(w, http.StatusInternalServerError, "logs.stream_unsupported", "log streaming is not supported", nil)
		return
	}
	level := parseLogLevel(r.URL.Query().Get("level"))
	entries, unsubscribe := s.logBuffer.Subscribe()
	defer unsubscribe()

	w.Header().Set("Content-Type", "text/event-stream; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("Connection", "keep-alive")
	w.WriteHeader(http.StatusOK)
	_, _ = io.WriteString(w, ": connected\n\n")
	flusher.Flush()

	heartbeat := time.NewTicker(25 * time.Second)
	defer heartbeat.Stop()
	for {
		select {
		case <-s.shutdown:
			return
		case <-r.Context().Done():
			return
		case <-heartbeat.C:
			_, _ = io.WriteString(w, ": heartbeat\n\n")
			flusher.Flush()
		case entry, ok := <-entries:
			if !ok {
				return
			}
			if logEntryLevel(entry) < level {
				continue
			}
			if err := writeLogSSE(w, entry); err != nil {
				return
			}
			flusher.Flush()
		}
	}
}

func (s *Server) validateConfig(w http.ResponseWriter, r *http.Request) {
	cfg, err := s.decodeEditableConfig(r)
	if err != nil {
		writeValidationError(w, http.StatusBadRequest, err, "request.invalid_json")
		return
	}
	current, err := config.Load(s.configPath)
	if err != nil {
		writeValidationError(w, http.StatusInternalServerError, newCodedError("config.load_failed", "config load failed", nil), "config.load_failed")
		return
	}
	if err := applyBackendSecretActions(cfg, current); err != nil {
		writeValidationError(w, http.StatusOK, err, "secret.invalid_action")
		return
	}
	if err := applySubSecretActions(cfg, current); err != nil {
		writeValidationError(w, http.StatusOK, err, "subscription.access_code.invalid")
		return
	}
	if err := cfg.ValidateEditable(); err != nil {
		writeConfigValidationError(w, http.StatusOK, err)
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"valid": true})
}

func (s *Server) testBackend(w http.ResponseWriter, r *http.Request) {
	var req editableBackend
	dec := json.NewDecoder(io.LimitReader(r.Body, maxConfigBodySize+1))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		writeAdminError(w, http.StatusBadRequest, "request.invalid_json", "invalid backend test json", map[string]any{"target": "backend"})
		return
	}
	backend := config.Backend{
		ID:             req.ID,
		Server:         req.Server,
		AuthType:       req.AuthType,
		APIKey:         req.APIKey,
		APIKeyAction:   req.APIKeyAction,
		User:           req.User,
		Password:       req.Password,
		PasswordAction: req.PasswordAction,
		Version:        req.Version,
	}
	current, err := config.Load(s.configPath)
	if err != nil {
		writeAdminError(w, http.StatusInternalServerError, "config.load_failed", "config load failed", nil)
		return
	}
	testCfg := config.Config{Backends: []config.Backend{backend}, Subs: []config.Subscription{}}
	if err := applyBackendSecretActions(&testCfg, current); err != nil {
		writeAdminErrorFromError(w, http.StatusBadRequest, err, "secret.invalid_action")
		return
	}
	if err := testCfg.ValidateEditable(); err != nil {
		writeConfigAdminError(w, http.StatusBadRequest, err)
		return
	}
	client := openlist.NewClient(&http.Client{Timeout: 12 * time.Second}, s.logger)
	ctx, cancel := context.WithTimeout(r.Context(), 12*time.Second)
	defer cancel()
	if _, err := client.List(ctx, testCfg.Backends[0], "/", ""); err != nil {
		if s.logger != nil {
			s.logger.Warn("admin backend test failed", "backend", testCfg.Backends[0].ID, "auth_type", testCfg.Backends[0].AuthType, "error_kind", backendTestErrorKind(err))
		}
		writeAdminError(w, http.StatusBadGateway, "backend.test_failed", "backend test failed", nil)
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "message": "backend test passed"})
}

func (s *Server) putConfig(w http.ResponseWriter, r *http.Request) {
	next, err := s.decodeEditableConfig(r)
	if err != nil {
		writeAdminErrorFromError(w, http.StatusBadRequest, err, "request.invalid_json")
		return
	}
	s.saveMu.Lock()
	defer s.saveMu.Unlock()
	current, err := config.Load(s.configPath)
	if err != nil {
		writeAdminError(w, http.StatusInternalServerError, "config.load_failed", "config load failed", nil)
		return
	}
	if err := applyBackendSecretActions(next, current); err != nil {
		writeAdminErrorFromError(w, http.StatusBadRequest, err, "secret.invalid_action")
		return
	}
	if err := applySubSecretActions(next, current); err != nil {
		writeAdminErrorFromError(w, http.StatusBadRequest, err, "subscription.access_code.invalid")
		return
	}
	validated := cloneConfig(*next)
	if err := validated.ValidateEditable(); err != nil {
		writeConfigAdminError(w, http.StatusBadRequest, err)
		return
	}
	if err := saveJSONConfigAtomic(s.configPath, next); err != nil {
		writeAdminError(w, http.StatusInternalServerError, "config.save_failed", "config save failed", nil)
		return
	}
	if s.onSaved != nil {
		s.onSaved(&validated)
	} else {
		s.ApplyConfig(&validated)
	}
	if s.logger != nil {
		s.logger.Info("admin config saved", "path", s.configPath, "backends", len(validated.Backends), "subs", len(validated.Subs))
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "message": "config saved"})
}

func (s *Server) ApplyConfig(cfg *config.Config) {
	s.setTrustXForwardedFor(cfg.TrustXForwardedFor)
	s.setPublicBaseURL(cfg.PublicBaseURL)
}

func (s *Server) setTrustXForwardedFor(trust bool) {
	s.trustMu.Lock()
	defer s.trustMu.Unlock()
	s.trustXFF = trust
}

func (s *Server) trustXForwardedFor() bool {
	s.trustMu.RLock()
	defer s.trustMu.RUnlock()
	return s.trustXFF
}

func (s *Server) setPublicBaseURL(baseURL string) {
	s.trustMu.Lock()
	defer s.trustMu.Unlock()
	s.publicBaseURL = strings.TrimRight(strings.TrimSpace(baseURL), "/")
}

func (s *Server) getPublicBaseURL() string {
	s.trustMu.RLock()
	defer s.trustMu.RUnlock()
	return s.publicBaseURL
}

func (s *Server) index(w http.ResponseWriter, r *http.Request) {
	data, err := adminAssets.ReadFile("assets/index.html")
	if err != nil {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(data)
}

func (s *Server) asset(w http.ResponseWriter, r *http.Request) {
	name := strings.TrimPrefix(r.URL.Path, "/admin/assets/")
	if name == "" || strings.Contains(name, "\\") || strings.Contains(name, "..") {
		http.NotFound(w, r)
		return
	}
	path := "assets/" + name
	data, err := adminAssets.ReadFile(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			http.NotFound(w, r)
			return
		}
		writeJSON(w, http.StatusInternalServerError, map[string]any{"error": "admin asset load failed"})
		return
	}
	if contentType := mime.TypeByExtension(filepath.Ext(path)); contentType != "" {
		w.Header().Set("Content-Type", contentType)
	}
	w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
	w.Header().Set("Content-Length", fmt.Sprint(len(data)))
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(data)
}

func (s *Server) decodeEditableConfig(r *http.Request) (*config.Config, error) {
	var editable editableConfig
	dec := json.NewDecoder(io.LimitReader(r.Body, maxConfigBodySize+1))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&editable); err != nil {
		return nil, errors.New("invalid config json")
	}
	cfg := editable.Config()
	return &cfg, nil
}

func applyBackendSecretActions(next *config.Config, current *config.Config) error {
	currentByID := map[string]config.Backend{}
	for _, b := range current.Backends {
		currentByID[b.ID] = b
	}
	for i := range next.Backends {
		b := &next.Backends[i]
		actions := backendSecretActions(*b)
		currentBackend, hasCurrent := currentByID[b.ID]
		switch b.AuthType {
		case "api_key":
			action := defaultAction(actions["api_key"])
			if err := applySecretAction(action, &b.APIKey, currentBackend.APIKey, hasCurrent); err != nil {
				return codedf(errorCode(err, "secret.invalid_action"), map[string]any{"backend_id": b.ID, "secret": "api_key"}, "backend %q api_key_action: %v", b.ID, err)
			}
		case "password":
			action := defaultAction(actions["password"])
			if err := applySecretAction(action, &b.Password, currentBackend.Password, hasCurrent); err != nil {
				return codedf(errorCode(err, "secret.invalid_action"), map[string]any{"backend_id": b.ID, "secret": "password"}, "backend %q password_action: %v", b.ID, err)
			}
		default:
			b.APIKey = ""
			b.Password = ""
		}
		b.APIKeyAction = ""
		b.PasswordAction = ""
	}
	return nil
}

func applySubSecretActions(next *config.Config, current *config.Config) error {
	currentByID := map[string]config.Subscription{}
	for _, sub := range current.Subs {
		currentByID[sub.ID] = sub
	}
	for i := range next.Subs {
		sub := &next.Subs[i]
		currentSub, hasCurrent := currentByID[sub.ID]
		action := defaultAction(sub.AccessCodeHashAction)
		if strings.TrimSpace(sub.AccessCode) != "" {
			hash, err := auth.HashPassword(strings.TrimSpace(sub.AccessCode))
			if err != nil {
				return codedf("subscription.access_code.invalid", map[string]any{"sub_id": sub.ID, "min": 4, "max": 12}, "sub %q access_code: %v", sub.ID, err)
			}
			sub.AccessCodeHash = hash
			action = "replace"
		}
		if err := applySecretAction(action, &sub.AccessCodeHash, currentSub.AccessCodeHash, hasCurrent); err != nil {
			return codedf(errorCode(err, "secret.invalid_action"), map[string]any{"sub_id": sub.ID, "secret": "access_code"}, "sub %q access_code_hash_action: %v", sub.ID, err)
		}
		sub.AccessCode = ""
		sub.AccessCodeHashAction = ""
	}
	return nil
}

func backendSecretActions(b config.Backend) map[string]string {
	return map[string]string{"api_key": b.APIKeyAction, "password": b.PasswordAction}
}

func defaultAction(action string) string {
	action = strings.TrimSpace(action)
	if action == "" {
		return "replace"
	}
	return action
}

func applySecretAction(action string, target *string, current string, hasCurrent bool) error {
	switch action {
	case "keep":
		if !hasCurrent {
			return newCodedError("secret.keep_missing", "cannot keep missing existing secret", nil)
		}
		*target = current
	case "replace":
	case "clear":
		*target = ""
	default:
		return newCodedError("secret.invalid_action", "must be keep, replace or clear", map[string]any{"action": action})
	}
	return nil
}

func saveJSONConfigAtomic(path string, cfg *config.Config) error {
	validateCfg := cloneConfig(*cfg)
	if err := validateCfg.ValidateEditable(); err != nil {
		return err
	}
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp.")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	cleanup := true
	defer func() {
		if cleanup {
			_ = os.Remove(tmpPath)
		}
	}()
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	tmpData, err := os.ReadFile(tmpPath)
	if err != nil {
		return err
	}
	var reloaded config.Config
	if err := json.Unmarshal(tmpData, &reloaded); err != nil {
		return err
	}
	if err := reloaded.ValidateEditable(); err != nil {
		return err
	}
	if _, err := os.Stat(path); err == nil {
		backupPath := path + ".bak"
		tmpBackup, err := os.CreateTemp(dir, filepath.Base(backupPath)+".tmp.")
		if err != nil {
			return err
		}
		tmpBackupPath := tmpBackup.Name()
		if err := tmpBackup.Close(); err != nil {
			_ = os.Remove(tmpBackupPath)
			return err
		}
		backupCleanup := true
		defer func() {
			if backupCleanup {
				_ = os.Remove(tmpBackupPath)
			}
		}()
		if err := copyFile(path, tmpBackupPath); err != nil {
			return err
		}
		if err := os.Remove(backupPath); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if err := os.Rename(tmpBackupPath, backupPath); err != nil {
			return err
		}
		backupCleanup = false
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return err
	}
	cleanup = false
	return nil
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
	if err != nil {
		return err
	}
	defer out.Close()
	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Close()
}

func cloneConfig(cfg config.Config) config.Config {
	out := cfg
	out.Backends = append([]config.Backend(nil), cfg.Backends...)
	out.Subs = make([]config.Subscription, len(cfg.Subs))
	for i, sub := range cfg.Subs {
		out.Subs[i] = cloneSubscription(sub)
	}
	return out
}

func cloneSubscription(sub config.Subscription) config.Subscription {
	out := sub
	out.Lives = append([]config.Live(nil), sub.Lives...)
	out.Mounts = make([]config.Mount, len(sub.Mounts))
	for i, mount := range sub.Mounts {
		out.Mounts[i] = mount
		if mount.Params != nil {
			out.Mounts[i].Params = cloneStringMap(mount.Params)
		}
		if mount.PlayHeaders != nil {
			out.Mounts[i].PlayHeaders = cloneStringMap(mount.PlayHeaders)
		}
	}
	return out
}

func cloneStringMap(in map[string]string) map[string]string {
	out := make(map[string]string, len(in))
	for key, value := range in {
		out[key] = value
	}
	return out
}

type editableConfig struct {
	PublicBaseURL      string                 `json:"public_base_url"`
	TrustXForwardedFor bool                   `json:"trust_x_forwarded_for"`
	TVBox              config.TVBox           `json:"tvbox"`
	Backends           []editableBackend      `json:"backends"`
	Subs               []editableSubscription `json:"subs"`
}

type editableBackend struct {
	ID             string `json:"id"`
	Server         string `json:"server"`
	AuthType       string `json:"auth_type"`
	APIKey         string `json:"api_key,omitempty"`
	APIKeyAction   string `json:"api_key_action,omitempty"`
	User           string `json:"user,omitempty"`
	Password       string `json:"password,omitempty"`
	PasswordAction string `json:"password_action,omitempty"`
	Version        string `json:"version"`
	APIKeySet      bool   `json:"api_key_set"`
	PasswordSet    bool   `json:"password_set"`
}

type editableSubscription struct {
	ID                   string         `json:"id"`
	Path                 string         `json:"path,omitempty"`
	AccessCodeHash       string         `json:"access_code_hash,omitempty"`
	AccessCodeHashAction string         `json:"access_code_hash_action,omitempty"`
	AccessCodeHashSet    bool           `json:"access_code_hash_set"`
	AccessCode           string         `json:"access_code,omitempty"`
	SiteKey              string         `json:"site_key,omitempty"`
	SiteName             string         `json:"site_name,omitempty"`
	TVBox                config.TVBox   `json:"tvbox,omitempty"`
	Lives                []config.Live  `json:"lives,omitempty"`
	Mounts               []config.Mount `json:"mounts,omitempty"`
}

func (c editableConfig) Config() config.Config {
	cfg := config.Config{
		PublicBaseURL:      c.PublicBaseURL,
		TrustXForwardedFor: c.TrustXForwardedFor,
		TVBox:              c.TVBox,
		Backends:           make([]config.Backend, 0, len(c.Backends)),
		Subs:               make([]config.Subscription, 0, len(c.Subs)),
	}
	for _, b := range c.Backends {
		cfg.Backends = append(cfg.Backends, config.Backend{
			ID:             b.ID,
			Server:         b.Server,
			AuthType:       b.AuthType,
			APIKey:         b.APIKey,
			APIKeyAction:   b.APIKeyAction,
			User:           b.User,
			Password:       b.Password,
			PasswordAction: b.PasswordAction,
			Version:        b.Version,
		})
	}
	for _, sub := range c.Subs {
		cfg.Subs = append(cfg.Subs, config.Subscription{
			ID:                   sub.ID,
			Path:                 sub.Path,
			AccessCodeHash:       sub.AccessCodeHash,
			AccessCodeHashAction: sub.AccessCodeHashAction,
			AccessCode:           sub.AccessCode,
			SiteKey:              sub.SiteKey,
			SiteName:             sub.SiteName,
			TVBox:                sub.TVBox,
			Lives:                sub.Lives,
			Mounts:               sub.Mounts,
		})
	}
	return cfg
}

type redactedBackend struct {
	ID             string `json:"id"`
	Server         string `json:"server"`
	AuthType       string `json:"auth_type"`
	User           string `json:"user,omitempty"`
	Version        string `json:"version"`
	APIKeySet      bool   `json:"api_key_set"`
	PasswordSet    bool   `json:"password_set"`
	APIKeyAction   string `json:"api_key_action"`
	PasswordAction string `json:"password_action"`
}

type redactedSubscription struct {
	ID                   string         `json:"id"`
	Path                 string         `json:"path,omitempty"`
	AccessCodeHashSet    bool           `json:"access_code_hash_set"`
	AccessCodeHashAction string         `json:"access_code_hash_action"`
	SiteKey              string         `json:"site_key,omitempty"`
	SiteName             string         `json:"site_name,omitempty"`
	TVBox                config.TVBox   `json:"tvbox,omitempty"`
	Lives                []config.Live  `json:"lives,omitempty"`
	Mounts               []config.Mount `json:"mounts,omitempty"`
}

func redactedConfig(cfg config.Config) map[string]any {
	backends := make([]redactedBackend, 0, len(cfg.Backends))
	for _, b := range cfg.Backends {
		item := redactedBackend{
			ID:             b.ID,
			Server:         b.Server,
			AuthType:       b.AuthType,
			User:           b.User,
			Version:        b.Version,
			APIKeySet:      b.APIKey != "",
			PasswordSet:    b.Password != "",
			APIKeyAction:   "keep",
			PasswordAction: "keep",
		}
		backends = append(backends, item)
	}
	subs := make([]redactedSubscription, 0, len(cfg.Subs))
	for _, sub := range cfg.Subs {
		subs = append(subs, redactedSubscription{
			ID:                   sub.ID,
			Path:                 sub.Path,
			AccessCodeHashSet:    sub.AccessCodeHash != "",
			AccessCodeHashAction: "keep",
			SiteKey:              sub.SiteKey,
			SiteName:             sub.SiteName,
			TVBox:                sub.TVBox,
			Lives:                sub.Lives,
			Mounts:               sub.Mounts,
		})
	}
	return map[string]any{
		"public_base_url":       cfg.PublicBaseURL,
		"trust_x_forwarded_for": cfg.TrustXForwardedFor,
		"tvbox":                 cfg.TVBox,
		"backends":              backends,
		"subs":                  subs,
	}
}

type adminState struct {
	Hash          string
	SetupCodePath string
	SetupCode     string
}

func loadAdminState(configPath string) (adminState, error) {
	if code := strings.TrimSpace(os.Getenv(envAdminCode)); code != "" {
		hash, err := hashAdminCode(code)
		if err != nil {
			return adminState{}, err
		}
		return adminState{Hash: hash}, nil
	}
	if hash := strings.TrimSpace(os.Getenv(envAdminCodeHash)); hash != "" {
		if err := auth.ValidateHash(hash); err != nil {
			return adminState{}, fmt.Errorf("%s is not a valid bcrypt hash", envAdminCodeHash)
		}
		return adminState{Hash: hash}, nil
	}
	secretPath := adminSecretPath(configPath)
	data, err := os.ReadFile(secretPath)
	if err == nil {
		hash := strings.TrimSpace(string(data))
		if err := auth.ValidateHash(hash); err != nil {
			return adminState{}, fmt.Errorf("admin secret file contains invalid hash")
		}
		return adminState{Hash: hash}, nil
	}
	if !errors.Is(err, os.ErrNotExist) {
		return adminState{}, fmt.Errorf("read admin secret file: %w", err)
	}
	setupPath := adminSetupCodePath(configPath)
	if data, err := os.ReadFile(setupPath); err == nil {
		code := strings.TrimSpace(string(data))
		if err := validateAdminCode(code); err != nil {
			return adminState{}, fmt.Errorf("admin setup code file contains invalid code")
		}
		return adminState{SetupCodePath: setupPath, SetupCode: code}, nil
	}
	code, err := randomDigits(12)
	if err != nil {
		return adminState{}, err
	}
	if err := os.WriteFile(setupPath, []byte(code+"\n"), 0o600); err != nil {
		return adminState{}, fmt.Errorf("write admin setup code file: %w", err)
	}
	return adminState{SetupCodePath: setupPath, SetupCode: code}, nil
}

func adminSecretPath(configPath string) string {
	return filepath.Join(filepath.Dir(configPath), secretFileName)
}

func adminSetupCodePath(configPath string) string {
	return filepath.Join(filepath.Dir(configPath), setupCodeFileName)
}

func randomDigits(length int) (string, error) {
	buf := make([]byte, length)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	for i := range buf {
		buf[i] = '0' + (buf[i] % 10)
	}
	return string(buf), nil
}

func hashAdminCode(code string) (string, error) {
	if err := validateAdminCode(code); err != nil {
		return "", newCodedError("admin.access_code.invalid", err.Error(), map[string]any{"min": 8, "max": 64})
	}
	hash, err := bcrypt.GenerateFromPassword([]byte(code), adminBcryptCost)
	if err != nil {
		return "", err
	}
	return string(hash), nil
}

func verifyAdminCode(hash, code string) error {
	if err := validateAdminCode(code); err != nil {
		return err
	}
	hash = strings.TrimSpace(hash)
	if strings.HasPrefix(hash, "$2y$") {
		hash = "$2a$" + strings.TrimPrefix(hash, "$2y$")
	}
	return bcrypt.CompareHashAndPassword([]byte(hash), []byte(code))
}

func verifySetupCode(want, got string) error {
	if err := validateAdminCode(got); err != nil {
		return err
	}
	if subtleConstantTimeCompare(want, got) {
		return nil
	}
	return errors.New("invalid setup code")
}

func subtleConstantTimeCompare(a, b string) bool {
	if len(a) != len(b) {
		return false
	}
	var diff byte
	for i := range a {
		diff |= a[i] ^ b[i]
	}
	return diff == 0
}

func validateAdminCode(code string) error {
	if len(code) < 8 || len(code) > 64 {
		return errors.New("admin access code must be 8 to 64 characters")
	}
	for _, r := range code {
		if r <= 32 || r == 127 {
			return errors.New("admin access code must not contain whitespace or control characters")
		}
	}
	return nil
}

func (s *Server) adminFailureKey(r *http.Request) string {
	return "admin|" + auth.ClientHost(r, s.trustXForwardedFor())
}

func (s *Server) setupFailureKey(r *http.Request) string {
	return "setup|" + auth.ClientHost(r, s.trustXForwardedFor())
}

func (s *Server) logAuthFailure(message string, r *http.Request, reason string) {
	if s.logger == nil {
		return
	}
	s.logger.Warn(message, "client", auth.ClientHost(r, s.trustXForwardedFor()), "reason", reason)
}

func backendTestErrorKind(err error) string {
	if err == nil {
		return ""
	}
	msg := err.Error()
	switch {
	case strings.Contains(msg, "authorization"):
		return "authorization"
	case strings.Contains(msg, "permission denied"):
		return "permission"
	case strings.Contains(msg, "openlist request failed"):
		return "request"
	case strings.Contains(msg, "openlist"):
		return "upstream"
	default:
		return "unknown"
	}
}

func parseLogLimit(value string, fallback, max int) int {
	limit, err := strconv.Atoi(strings.TrimSpace(value))
	if err != nil || limit <= 0 {
		return fallback
	}
	if limit > max {
		return max
	}
	return limit
}

func parseLogLevel(value string) slog.Level {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "debug":
		return slog.LevelDebug
	case "warn", "warning":
		return slog.LevelWarn
	case "error":
		return slog.LevelError
	default:
		return slog.LevelInfo
	}
}

func logEntryLevel(entry logging.Entry) slog.Level {
	switch entry.Level {
	case slog.LevelDebug.String():
		return slog.LevelDebug
	case slog.LevelWarn.String():
		return slog.LevelWarn
	case slog.LevelError.String():
		return slog.LevelError
	default:
		return slog.LevelInfo
	}
}

func writeLogSSE(w io.Writer, entry logging.Entry) error {
	data, err := json.Marshal(entry)
	if err != nil {
		return err
	}
	if _, err := io.WriteString(w, "event: log\n"); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "data: "); err != nil {
		return err
	}
	if _, err := w.Write(data); err != nil {
		return err
	}
	_, err = io.WriteString(w, "\n\n")
	return err
}

func adminURL(listen string) string {
	host := listen
	if strings.HasPrefix(host, ":") {
		host = "127.0.0.1" + host
	}
	return "http://" + host + "/admin"
}

func (s *Server) issueSessionCookie(w http.ResponseWriter, r *http.Request) error {
	token, err := randomToken(32)
	if err != nil {
		return err
	}
	now := time.Now()
	expires := now.Add(sessionTTL)
	s.sessionMu.Lock()
	s.pruneExpiredSessionsLocked(now)
	s.pruneOldestSessionsLocked(maxAdminSessions - 1)
	s.sessions[token] = adminSession{CreatedAt: now, ExpiresAt: expires}
	s.sessionMu.Unlock()
	http.SetCookie(w, s.sessionCookie(r, token, expires, int(sessionTTL.Seconds())))
	return nil
}

func (s *Server) validSession(r *http.Request) bool {
	cookie, err := r.Cookie(sessionCookieName)
	if err != nil || cookie.Value == "" {
		return false
	}
	now := time.Now()
	s.sessionMu.Lock()
	defer s.sessionMu.Unlock()
	session, ok := s.sessions[cookie.Value]
	if !ok {
		return false
	}
	if !session.ExpiresAt.After(now) {
		delete(s.sessions, cookie.Value)
		return false
	}
	return true
}

func (s *Server) pruneExpiredSessionsLocked(now time.Time) {
	for token, session := range s.sessions {
		if !session.ExpiresAt.After(now) {
			delete(s.sessions, token)
		}
	}
}

func (s *Server) pruneOldestSessionsLocked(max int) {
	for len(s.sessions) > max {
		var oldestToken string
		var oldestCreatedAt time.Time
		for token, session := range s.sessions {
			if oldestToken == "" || session.CreatedAt.Before(oldestCreatedAt) {
				oldestToken = token
				oldestCreatedAt = session.CreatedAt
			}
		}
		delete(s.sessions, oldestToken)
	}
}

func randomToken(length int) (string, error) {
	buf := make([]byte, length)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}

func (s *Server) clearSessionCookie(w http.ResponseWriter, r *http.Request) {
	http.SetCookie(w, s.sessionCookie(r, "", time.Unix(0, 0), -1))
}

func (s *Server) sessionCookie(r *http.Request, value string, expires time.Time, maxAge int) *http.Cookie {
	return &http.Cookie{
		Name:     sessionCookieName,
		Value:    value,
		Path:     "/admin",
		Expires:  expires,
		MaxAge:   maxAge,
		HttpOnly: true,
		Secure:   s.sessionCookieSecure(r),
		SameSite: http.SameSiteStrictMode,
	}
}

func (s *Server) sessionCookieSecure(r *http.Request) bool {
	if baseURL := s.getPublicBaseURL(); baseURL != "" {
		u, err := url.Parse(baseURL)
		if err == nil && strings.EqualFold(u.Scheme, "https") {
			return true
		}
	}
	return s.requestIsHTTPS(r)
}

func (s *Server) requestIsHTTPS(r *http.Request) bool {
	return r.TLS != nil || (s.trustXForwardedFor() && strings.EqualFold(r.Header.Get("X-Forwarded-Proto"), "https"))
}

func (s *Server) sameOrigin(r *http.Request) bool {
	origin := strings.TrimSpace(r.Header.Get("Origin"))
	if origin != "" {
		return s.originMatchesRequest(r, origin)
	}
	referer := strings.TrimSpace(r.Header.Get("Referer"))
	if referer != "" {
		return s.originMatchesRequest(r, referer)
	}
	return true
}

func (s *Server) originMatchesRequest(r *http.Request, raw string) bool {
	u, err := url.Parse(raw)
	if err != nil || u.Scheme == "" || u.Host == "" {
		return false
	}
	want, err := url.Parse(s.adminBaseURL(r))
	if err != nil || want.Scheme == "" || want.Host == "" {
		return false
	}
	return strings.EqualFold(u.Scheme, want.Scheme) && strings.EqualFold(u.Host, want.Host)
}

func (s *Server) adminBaseURL(r *http.Request) string {
	if baseURL := s.getPublicBaseURL(); baseURL != "" {
		return baseURL
	}
	scheme := "http"
	if s.requestIsHTTPS(r) {
		scheme = "https"
	}
	host := r.Host
	if host == "" {
		host = "localhost"
	}
	return scheme + "://" + host
}

func writeJSON(w http.ResponseWriter, status int, value any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(value)
}

func writeAdminError(w http.ResponseWriter, status int, code, message string, params map[string]any) {
	body := map[string]any{"ok": false, "error": message, "error_code": code}
	if len(params) > 0 {
		body["error_params"] = params
	}
	writeJSON(w, status, body)
}

func writeAdminErrorFromError(w http.ResponseWriter, status int, err error, fallbackCode string) {
	writeAdminError(w, status, errorCode(err, fallbackCode), err.Error(), errorParams(err))
}

func writeConfigAdminError(w http.ResponseWriter, status int, err error) {
	writeAdminError(w, status, config.ErrorCode(err, "config.invalid"), err.Error(), config.ErrorParams(err))
}

func writeValidationError(w http.ResponseWriter, status int, err error, fallbackCode string) {
	body := map[string]any{"valid": false, "error": err.Error(), "error_code": errorCode(err, fallbackCode)}
	if params := errorParams(err); len(params) > 0 {
		body["error_params"] = params
	}
	writeJSON(w, status, body)
}

func writeConfigValidationError(w http.ResponseWriter, status int, err error) {
	body := map[string]any{"valid": false, "error": err.Error(), "error_code": config.ErrorCode(err, "config.invalid")}
	if params := config.ErrorParams(err); len(params) > 0 {
		body["error_params"] = params
	}
	writeJSON(w, status, body)
}
